### ISSUE TITLE
Plastid sequences

### ISSUE THREAD

**Issue by rspreafico** [vaulot/pr2database#10]
Hi! Congrats for the great work!

From the README, we can see that plastid sequences are included in PR2. At the bottom, a reference to a plastid-only DB (PhytoREF) is provided. I guess it is not clear to what extent plastid sequences in PR2 overlap with PhytoREF, or whether PR2 is a superset of PhytoREF. In case it is not, and one wants to merge the two DBs, would dereplication be suggested?

Thank you.

**Comment by vaulot** [comment]
Hi

Sorry for the confusion, but at present the plastid 16S rRNA sequences are not included in the PR2.  We are planning to include the whole PhytoRef into PR2 at a latter date .  So at present no dereplication needed.  Cheers. Daniel

**Comment by rspreafico-sgi** [comment]
Thank you for the fast reply and for amending the readme file. Would this sentence in the readme file also require amendments?

> The database mainly consists of nuclear-encoded protistan sequences. However, metazoans, land plants, macrosporic fungi and eukaryotic organelles (mitochondrion, plastid and others) are also included because they are useful for the analysis of high-troughput sequencing data sets.

I will download the plastid sequences from PhytoREF. Do you have a recommended source for mitochondrial rRNA sequences, or maybe a section of early releases of PR2 when they still included mitochondrial sequences?

**Comment by vaulot** [comment]
> Thank you for the fast reply and for amending the readme file. Would this sentence in the readme file also require amendments?

>>The database mainly consists of nuclear-encoded protistan sequences. However, metazoans, land plants, macrosporic fungi and eukaryotic organelles (mitochondrion, plastid and others) are also included because they are useful for the analysis of high-troughput sequencing data sets.

Yes absolutely, done now.

> I  will download the plastid sequences from PhytoREF. Do you have a recommended source for mitochondrial rRNA sequences, or maybe a section of early releases of PR2 when they still included mitochondrial sequences?

I will try to do some archaeology but unfortunately the PR2 server is long gone and had never been mirrored.   I will get back to you if I find anything and if I do not, will add this on my to do list.

Thanks a lot for your feedback.

**Comment by rspreafico** [comment]
Thank you for looking into this!
