### ISSUE TITLE
Missing Sequence

### ISSUE THREAD

**Issue by jwalser** [vaulot/pr2database#11]
Hello there,

first of all, thanks for making this database available!

This is not a big problem but just something I noticed. I am using file: pr2_version_4.10.0_UTAX.fasta and got a warning formatting it: 

WARNING: **Empty sequence** at line 2598276 in FASTA file /cluster/project/gdc/people/jwalser/db/pr2_version_4.10.0_UTAX.fasta, label >CP000499.0.0_U;tax=k:Eukaryota,d:Opisthokonta,p:Fungi,c:Ascomycota,o:Saccharomycotina,f:Saccharomycetales,g:Scheffersomyces,s:Scheffersomyces_stipitis

Adding the trimmed sequences (or removing the record it) solved it.

Best

**Comment by vaulot** [comment]
Hello

Thanks for the feedback, this will be fixed in the next release of PR2 (4.11.0) which should be released in a couple of weeks.  Cheers.  Daniel
