### ISSUE TITLE
Troubleshoot for generating reference database for blast analysis

### ISSUE THREAD

**Issue by ChetanGaonkar** [vaulot/pr2database#9]
Dear Users,
There is an error in the PR2 dataset (pr2_version_4.10.0_mothur.fasta).
The sequence Id CP000499.0.0_U is without a nucleotide sequence. 
This creates an error for generating reference database for blast analysis.
You have to eliminate this sequence id from the dataset before you carry on with the make local dataset. 
Hope this helps,
Regards,
Chetan

![image](https://user-images.githubusercontent.com/40350385/41520666-c5459f6c-7309-11e8-99bf-e7f0bb784062.png)

**Comment by vaulot** [comment]
Dear Chetan

Thanks for finding the bug.  This will be fixed in the next release of the database, 4.11.0, hopefully to come out in July.  Cheers.  Daniel
